# Welcome to jupyter notebook


In [1]:
import numpy as py

In [2]:
arr = py.arrar([1,2,3,4])

AttributeError: module 'numpy' has no attribute 'arrar'

In [ ]:
arr = py.array([1,4,5,6])

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
arr1 = py.array([1,3,4,5])

In [ ]:
arr2 = py.array([2,4,5,6])

In [ ]:
arrsum = arr1+arr2

In [ ]:
arrsum

In [ ]:
arr

In [ ]:
arrr = py.array([[1,3,4,5], [4,5,6,7], [3,6,9,5]])

In [ ]:
arrr

In [ ]:
arrr.shape

In [ ]:
arr.dtype

In [ ]:
arry = py.array([[1,4,5,6], [4,5,6,7], [3,5,7,8]])

In [ ]:
mulSum = arrr+arry

In [ ]:
mulSum

In [ ]:
mul = arrr * arry

In [ ]:
mul

In [4]:
py.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [6]:
py.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b = py.zeros([2,2])

In [10]:
b


array([[0., 0.],
       [0., 0.]])

In [12]:
c = py.array([1,2,34])

In [14]:
c[0] =23

In [16]:
c

array([23,  2, 34])

In [18]:
b[0,2] = 12

IndexError: index 2 is out of bounds for axis 1 with size 2

In [20]:
b.shape

(2, 2)

In [22]:
b[0,1] = 12

In [24]:
b

array([[ 0., 12.],
       [ 0.,  0.]])

In [26]:
b[0,0] = 13

In [28]:
b

array([[13., 12.],
       [ 0.,  0.]])

In [30]:
py.array({22,3,4})

array({3, 4, 22}, dtype=object)

In [32]:
d = py.zeros([6,8])

In [35]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
d.range


AttributeError: 'numpy.ndarray' object has no attribute 'range'

In [39]:
d.arange

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [41]:
py.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [43]:
np.identity(3,3)

NameError: name 'np' is not defined

In [45]:
id

<function id(obj, /)>

In [47]:
py.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
ide = py.identity(4)

In [52]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
ide.size

16

In [56]:
ide.shape

(4, 4)

In [ ]:
emp = py.empty(2,2)

In [59]:
emp


NameError: name 'emp' is not defined

In [61]:
empt = py.empty((2,2))

In [64]:
empt

array([[1., 1.],
       [1., 1.]])

In [66]:
empy = py.empty((34,34))

In [68]:
empy

array([[ 4.94065646e-324,  2.52961611e-321,  6.95171553e-310, ...,
                     nan,  6.89799718e-307,              nan],
       [             nan,  1.25160405e-308,  4.72835834e-308, ...,
                     nan,              nan,              nan],
       [             nan,              nan,              nan, ...,
                     nan,  1.11253693e-306,  5.56268465e-309],
       ...,
       [-8.74320333e-113,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000, -6.11147805e-112],
       [ 0.00000000e+000,  0.00000000e+000, -8.74320333e-113, ...,
         0.00000000e+000, -2.82348770e-210,  0.00000000e+000],
       [ 0.00000000e+000, -6.11147805e-112,  0.00000000e+000, ...,
        -8.74320333e-113,  0.00000000e+000,  0.00000000e+000]])

In [70]:
arre = py.arange(45)

In [73]:
arre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [76]:
arre.reshape(2,4)

ValueError: cannot reshape array of size 45 into shape (2,4)

In [78]:
arre.reshape(2,22)

ValueError: cannot reshape array of size 45 into shape (2,22)

In [80]:
arrt = py.arange(44)

In [82]:
arrt

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [85]:
arrt.reshape(2,22)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43]])

In [88]:
arrt

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [91]:
arrt.reval()

AttributeError: 'numpy.ndarray' object has no attribute 'reval'

In [94]:
arrt.reval

AttributeError: 'numpy.ndarray' object has no attribute 'reval'

In [96]:
arrt.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [98]:
aay = arrt.reshape(4,11)

In [101]:
aay

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43]])

In [103]:
ayy = py.arange(100)

In [105]:
ayy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [107]:
ayy.reshape(5,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [110]:
ayy.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [114]:
evl=ayy.reshape(5,20)

In [115]:
avl

NameError: name 'avl' is not defined

In [117]:
evl

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [119]:
evl.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [121]:
ev.reval()

NameError: name 'ev' is not defined

In [123]:
evl.reval()

AttributeError: 'numpy.ndarray' object has no attribute 'reval'

In [125]:
evl

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [127]:
evl.reval()

AttributeError: 'numpy.ndarray' object has no attribute 'reval'

In [129]:
evl.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [131]:
x = [[1,2,3],[2,4,5], [2,5,7]]


In [133]:
x

[[1, 2, 3], [2, 4, 5], [2, 5, 7]]

In [136]:
ar = py.array(x)

In [137]:
ar

array([[1, 2, 3],
       [2, 4, 5],
       [2, 5, 7]])

In [139]:
ar.sum(axis=0)

array([ 5, 11, 15])

In [142]:
ar.sum(axis =1)

array([ 6, 11, 14])

In [144]:
ar.T

array([[1, 2, 2],
       [2, 4, 5],
       [3, 5, 7]])

In [146]:
ar.ndim

2

In [148]:
ar.flat

In [151]:
for item in ar.flat:
 print(item)

1
2
3
2
4
5
2
5
7


In [153]:
ar.size

9

In [155]:
ar.shape

(3, 3)

In [157]:
ar.nbytes

36

# find max and min index of array in 1D

In [161]:
one = py.array([1,3,45,3])

In [163]:
one

array([ 1,  3, 45,  3])

In [165]:
one.argmax()

2

In [167]:
one.argmin()

0

*  sort array element

In [170]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

# max,min and sort in 2D array

* indexes of max, min etc

In [174]:
two =ar

In [177]:
two

array([[1, 2, 3],
       [2, 4, 5],
       [2, 5, 7]])

In [179]:
two.argmax()

8

In [181]:
two.argmin()

0

In [183]:
two.argmax(axis =0)

array([1, 2, 2], dtype=int64)

In [185]:
two.argmax(axis= 1)

array([2, 2, 2], dtype=int64)

In [187]:
ar4=py.array([[1,2],[3,4]])

In [189]:
arr5 = py.array([[6,2], [3,1]])

In [192]:
ar4*arr5


array([[6, 4],
       [9, 4]])

* value

In [194]:
ar.max()

7

In [196]:
ar.min()

1

In [201]:
py.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 2.        , 2.23606798],
       [1.41421356, 2.23606798, 2.64575131]])

In [204]:
ar.sum()

31

* Find

In [207]:
ar

array([[1, 2, 3],
       [2, 4, 5],
       [2, 5, 7]])

In [210]:
py.where(ar>4)

(array([1, 2, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [212]:
type(py.where(ar>4))

tuple

In [214]:
py.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [218]:
ar[0,0] =0

In [220]:
py.nonzero(ar)


(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [222]:
pyarr = [1,2,4,5]

In [239]:
numpy_arr = py.array([1,2,4,5])

*** memory comparison btw python and numpy array ***

In [226]:
import sys

In [228]:
sys.getsizeof(1) * len(pyarr)

112

In [237]:
numpy_arr.itemsize * numpy_arr.size

24