# Welcome to jupyter notebook


In [1]:
import numpy as py

In [2]:
arr = py.arrar([1,2,3,4])

AttributeError: module 'numpy' has no attribute 'arrar'

In [ ]:
arr = py.array([1,4,5,6])

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
arr1 = py.array([1,3,4,5])

In [ ]:
arr2 = py.array([2,4,5,6])

In [ ]:
arrsum = arr1+arr2

In [ ]:
arrsum

In [ ]:
arr

In [ ]:
arrr = py.array([[1,3,4,5], [4,5,6,7], [3,6,9,5]])

In [ ]:
arrr

In [ ]:
arrr.shape

In [ ]:
arr.dtype

In [ ]:
arry = py.array([[1,4,5,6], [4,5,6,7], [3,5,7,8]])

In [ ]:
mulSum = arrr+arry

In [ ]:
mulSum

In [ ]:
mul = arrr * arry

In [ ]:
mul

In [4]:
py.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [6]:
py.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b = py.zeros([2,2])

In [10]:
b


array([[0., 0.],
       [0., 0.]])

In [12]:
c = py.array([1,2,34])

In [14]:
c[0] =23

In [16]:
c

array([23,  2, 34])

In [18]:
b[0,2] = 12

IndexError: index 2 is out of bounds for axis 1 with size 2

In [20]:
b.shape

(2, 2)

In [22]:
b[0,1] = 12

In [24]:
b

array([[ 0., 12.],
       [ 0.,  0.]])

In [26]:
b[0,0] = 13

In [28]:
b

array([[13., 12.],
       [ 0.,  0.]])

In [30]:
py.array({22,3,4})

array({3, 4, 22}, dtype=object)

In [32]:
d = py.zeros([6,8])

In [35]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
d.range


AttributeError: 'numpy.ndarray' object has no attribute 'range'

In [39]:
d.arange

AttributeError: 'numpy.ndarray' object has no attribute 'arange'

In [41]:
py.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [43]:
np.identity(3,3)

NameError: name 'np' is not defined

In [45]:
id

<function id(obj, /)>

In [47]:
py.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
ide = py.identity(4)

In [52]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
ide.size

16

In [56]:
ide.shape

(4, 4)

In [ ]:
emp = py.empty(2,2)

In [59]:
emp


NameError: name 'emp' is not defined

In [61]:
empt = py.empty((2,2))

In [64]:
empt

array([[1., 1.],
       [1., 1.]])

In [66]:
empy = py.empty((34,34))

In [68]:
empy

array([[ 4.94065646e-324,  2.52961611e-321,  6.95171553e-310, ...,
                     nan,  6.89799718e-307,              nan],
       [             nan,  1.25160405e-308,  4.72835834e-308, ...,
                     nan,              nan,              nan],
       [             nan,              nan,              nan, ...,
                     nan,  1.11253693e-306,  5.56268465e-309],
       ...,
       [-8.74320333e-113,  0.00000000e+000,  0.00000000e+000, ...,
         0.00000000e+000,  0.00000000e+000, -6.11147805e-112],
       [ 0.00000000e+000,  0.00000000e+000, -8.74320333e-113, ...,
         0.00000000e+000, -2.82348770e-210,  0.00000000e+000],
       [ 0.00000000e+000, -6.11147805e-112,  0.00000000e+000, ...,
        -8.74320333e-113,  0.00000000e+000,  0.00000000e+000]])

In [70]:
arre = py.arange(45)

In [73]:
arre

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [76]:
arre.reshape(2,4)

ValueError: cannot reshape array of size 45 into shape (2,4)

In [78]:
arre.reshape(2,22)

ValueError: cannot reshape array of size 45 into shape (2,22)

In [80]:
arrt = py.arange(44)

In [82]:
arrt

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [85]:
arrt.reshape(2,22)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
        38, 39, 40, 41, 42, 43]])