# Welcome to jupyter notebook


In [1]:
import numpy as py

In [2]:
arr = py.arrar([1,2,3,4])

AttributeError: module 'numpy' has no attribute 'arrar'

In [ ]:
arr = py.array([1,4,5,6])

In [ ]:
arr.shape

In [ ]:
arr.dtype

In [ ]:
arr1 = py.array([1,3,4,5])

In [ ]:
arr2 = py.array([2,4,5,6])

In [ ]:
arrsum = arr1+arr2

In [ ]:
arrsum

In [ ]:
arr

In [ ]:
arrr = py.array([[1,3,4,5], [4,5,6,7], [3,6,9,5]])

In [ ]:
arrr

In [ ]:
arrr.shape

In [ ]:
arr.dtype

In [ ]:
arry = py.array([[1,4,5,6], [4,5,6,7], [3,5,7,8]])

In [ ]:
mulSum = arrr+arry

In [ ]:
mulSum

In [ ]:
mul = arrr * arry

In [ ]:
mul

In [4]:
py.zeros(2,4)

TypeError: Cannot interpret '4' as a data type

In [6]:
py.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
b = py.zeros([2,2])

In [10]:
b


array([[0., 0.],
       [0., 0.]])

In [12]:
c = py.array([1,2,34])

In [14]:
c[0] =23

In [16]:
c

array([23,  2, 34])

In [18]:
b[0,2] = 12

IndexError: index 2 is out of bounds for axis 1 with size 2

In [20]:
b.shape

(2, 2)

In [ ]:
b